### ISSUE TITLE
AI powered NPC using Llama2 API

### ISSUE THREAD

**Issue by Sam2much96** [Sam2much96/Dystopia-App#115]

**Comment by Sam2much96** [comment]
Implement Llama2 API hosted on a server via API calls to implement NPC personalities

**Comment by ishaan-jaff** [comment]
Hi @Sam2much96  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`- You can use llama/gpt/claude (100+ LLMs)**

If you don't have access to certain LLMs you can use our proxy server or spin up your own proxy server using LiteLLM

## Usage
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
response = completion(model="llama2", messages=messages)
```

**Comment by Sam2much96** [comment]
Sweet. Thanks for your contribution! This issue has already been fixed and would likely be closed today once internal testing is finished

**Comment by Sam2much96** [comment]
Done
