### ISSUE TITLE
Comic book zooms in and button response 

### ISSUE THREAD

**Issue by Ehiiz** [Sam2much96/Dystopia-App#6]
Comic book zooms in and is all over the place. Also the touch pad does not respond sometimes

**Comment by Inhumanity96** [comment]
Multi-touch gestures wasnt properly implemented in the app. Double tap to zoom was added but alot of other Multi-touch gestures weren't. We'll fix it with the next update. An updated Multi-touch system for Touch devices

**Comment by Sam2much96** [comment]
Fixed
